### ISSUE TITLE
Public files take a incorrect file structure

### ISSUE THREAD

**Issue by encrypted-soul** [rafed/ramium#12]
The file structure after I render the public file is extremely inconvenient and takes

`dir1/dir2` instead of `dir1/dir2/index.html`

Please look into this.

**Comment by rafed** [comment]
It''s supposed to be like dir1/dir2/index.html. Can you link me the source and output?

**Comment by encrypted-soul** [comment]
> It''s supposed to be like dir1/dir2/index.html. Can you link me the source and output?

What are the files you want me to send?

**Comment by rafed** [comment]
the content directory structure, and the public folder

**Comment by encrypted-soul** [comment]
https://github.com/SirCharan/SirCharan.github.io/tree/master/blog

Here it is.
