### ISSUE TITLE
Example post fails to render on title in frontend

### ISSUE THREAD

**Issue by wsw70** [rafed/ramium#2]
After copying the frontmatter from the example post, Higo crashes with

```
"C:\temp\helloworld\content\posts\my-first-post.md:2:1": failed to unmarshal YAML: yaml: invalid map key: map[interface {}]interface {}{"replace .Name \"-\" \" \" | title":interface {}(nil)}

1 ---
2 title: {{ replace .Name "-" " " \| title }} 
3 date: {{ now.Format "2006-01-2" }} tags: [tag1, tag2]
```

Replacing the templates with strings removes the issue.

**Comment by rafed** [comment]
@wsw70 

Have you copied the config.toml from the examplesite? Setting title="something" in config.toml should fix it. If it still persists after this, link me the repo.
