### ISSUE TITLE
Dark toggle

### ISSUE THREAD

**Issue by bevsxyz** [rafed/ramium#3]
Hey have you tried adding a dark theme toggle. Ive been trying to add following [this](https://yonkov.github.io/post/add-dark-mode-toggle-to-hugo/) tutorial, but was only successful in making a toggle switch not actually changing the colors.

**Comment by bevsxyz** [comment]
I added this piece of code
```
body.dark-mode, 
body.dark-mode main * {
    background: rgb(45, 45, 45);
    color: #f5f5f5;
}

```
to ramium.css and you can see the result below
![Screenshot_2020-05-04_14-18-23](https://user-images.githubusercontent.com/60595515/80949735-36502900-8e12-11ea-8750-9a0257622736.png)

**Comment by bevsxyz** [comment]
Would greatly appreciate if you can include this feature by default. All other changes to partials were added in the site root /layout

**Comment by bevsxyz** [comment]
Or an automatic setting where the site chooses dark or light mode based on the browser settings as in the  hugo-coder theme

**Comment by rafed** [comment]
@chain-ed-reaction 

Thank you for taking an interest in Ramium. Although adding a dark mode was not what I had planned, I'll see if it is feasible to add it. It may take some time though.
