### ISSUE TITLE
Remove bold and...

### ISSUE THREAD

**Issue by jiapei100** [rafed/ramium#4]
1) How can I remove the **bold** for all words in the blog ?
2) It looks **&rsquo;m** is not resolved at the very Front page, but only when you click and open the blog ???
3) Where to add **author**?
4) Where to specify **sections**??

Please refer to [https://kind-feather.aerobaticapp.com/](https://kind-feather.aerobaticapp.com/) temporarily.... Thank you

**Comment by rafed** [comment]
1. All words in a blog post are not in bold. Or I didn't get what you meant.
2. What is 'm? Do you mean that apostrophe's are not rendering?
3. You can configure link to author in config.toml. Search for the author file in contents/addons/
4. In the contents folder, create a folder and place articles in there. the folder name will be rendered as a section.

**Comment by jiapei100** [comment]
@rafed 
Thank you so much !! 

1. Check [this page](https://kind-feather.aerobaticapp.com/posts/kicad/) . How can I change the fonts? It looks it's always **Haettenschweiler**
2. Yup, I'm talking about apostrophe's rendering in the front/FIRST page.

Thanks ....

**Comment by jiapei100** [comment]
@rafed 

Hi, rafed... What is the meaning of Sections? I was thinking it's something like categories ? In my understading, the categories/sections are used to categorize **ALL** blogs , instead of anything independent? 

- Tags: IMO, they are important keywords.
- Sections/Categories: every blog belongs to one of the sections/categories.
- Blogs: each blog belongs to a single section/category, but may have multiple tags/keywords.

That might be a bit different from your current design for **section**?

**Comment by rafed** [comment]
@jiapei100 

1. I never realized a shitty font was set as the first priority. My pc was rendering a fallbacked good one. Please check if the fonts are good now (and let me know here!)
2. Apostrophe's should be showing in the summary as well.

Furthermore, I realized your tags were not being rendered nicely. They should look better now.

To update the theme, go to themes/ramium/ and do a git pull

**Comment by rafed** [comment]
As for the design of the theme regarding tags/sections...

Imagine if you were to make a three part blog series on Java. The posts would be probably:
1. How to install Eclipse IDE
2. Hello world in Java
3. Functions in Java

Preferably these three topics should be grouped together as a "section". If it were placed in "posts" it would be jumbled up with the regular blog posts (i.e. posts that are a single entity, not related with other articles).

And thank you for taking an interest in Ramium. It makes me happy that I can be contribute for others.

**Comment by jiapei100** [comment]
@rafed 

Great... Now I understand... Sections/Categraries are good design... In such, **posts** contains independent posts .... Thank you ... close issue.

**Comment by jiapei100** [comment]
One more bug... 
Without a single post in **posts**, even if there are **posts under sections**, when you click on **All Posts**, nothing will show up...

**Comment by rafed** [comment]
As for this, I'm not sure how to design a solution for it. For now keep at least one article in the posts directory to avoid this. I might come up with something later.
