### ISSUE TITLE
Theme broken after latest updates

### ISSUE THREAD

**Issue by onedrawingperday** [rafed/ramium#7]
Hello again @rafed 

Currently the theme fails with the following ERROR

```
1. About Ramium.md:11:19": failed to extract shortcode: template for shortcode "local" not found
```

You need to add the missing shortcode or change what is called in the above content file.

Also please test whether a project using your theme generates properly before pushing updates.

Once you fix the above, feel free to close this issue.

Thank you.

**Comment by rafed** [comment]
Are you building with the latest commit? I have two sites deployed with the current commit, doesn't seem to have any problem. :/

**Comment by onedrawingperday** [comment]
@rafed 

Over here: https://github.com/rafed/ramium/blame/master/exampleSite/content/introduction-to-ramium/1.%20About%20Ramium.md#L11 you are referencing a non-existent `local` shortcode.

And yes the theme was updated with the latest commit on Hugo Themes today and it is broken.

**Comment by rafed** [comment]
My bad, had different contents across branches. Tested and fixed. Should be okay now. Thank you...

**Comment by onedrawingperday** [comment]
I just updated the theme with https://github.com/gohugoio/hugoThemes/commit/04444d1d0f52827bef9613b7a93cce478af1cb55 it should be ok.
