### ISSUE TITLE
Cannot add a favicon

### ISSUE THREAD

**Issue by ZZY2357** [rafed/ramium#9]
I put the `favicon.ico` into the `static/image` folder. But when I build it, it just put a `favicon.ico` into the root. Emmmmmm... It cannot show the favicon in Github Pages.

Thaks. :pray::pray::pray::pray::pray::pray::pray:

**Comment by rafed** [comment]
It should work. Try a hard refresh and see if it loads (Ctrl+F5)

Also by design, favicon.ico should be present at the root folder.
